#!/bin/bash

set -euo pipefail

function show_help {
local SCRIPT_NAME=$(basename "$0")
cat <<EOF
readonly SCRIPT_NAME=$(basename "$0")
cat <<EOF
Usage: $SCRIPT_NAME [-h] -s ssh-connection -p server-path
ssh-connection ssh server login string, example: example@example.com
server-path Path to set the ssh session from the login directory, example: sites/html/
EOF
}

declare SSH_CONNECTION=''
declare SERVER_PATH=''

while [ "$#" -gt 0 ]
do
	case "$1" in
	-h|--help)
		show_help
		exit 0
		;;
	-s|--ssh-connection)
		SSH_CONNECTION=$2
		shift
		;;
	-p|--server-path)
		SERVER_PATH=$2
		shift
		;;
	*)
		>&2 echo "Invalid option '$1'. Use --help to see the available options"
		exit 1
		;;
	esac
	shift
done

if [ -z "$SVN_URL" ]; then
	>&2 echo "The -s option is mandatory, use --help to see the available options"
	exit 1
fi

if [ -z "$SERVER_PATH" ]; then
	>&2 echo "The -p option is mandatory, use --help to see the available options"
	exit 1
fi

ssh "$SSH_CONN" -t "cd \"$SERVER_PATH\"; `echo $SHELL --login`"
