#!/bin/bash

set -e
set -u
set -o pipefail

declare FILENAME='.'
function show_help {
readonly SCRIPT_NAME=$(basename "$0")
cat <<EOF
Usage: $SCRIPT_NAME [options]
Updates a remote svn working copy SERVER_PATHectory showing a diff and asking for confirmation.

-h --help				shows this help message.
-y --skip-confirm 		option executes svn up without confirmation
-s --ssh-connection		ssh server login string, ie: example@example.com
-p --server-path 		path to the SERVER_PATHectory where the update will take place
-q --quiet				print only essential information and errors
filename				file that will be updated default: "$FILENAME"
EOF
}

#default options
declare SSH_CONNECTION=''
declare SERVER_PATH=''
declare CONFIRM=true
declare NOQUIET=true
declare QUIET_OPTION=''

while [ "$#" -gt 0 ]
do
	case "$1" in
	-h|--help)
		show_help
		exit 0
		;;
	-y|--skip-confirm)
		CONFIRM=false
		;;
	-s|--ssh-connection)
		SSH_CONNECTION=$2
		shift
		;;
	-p|--server-path)
		SERVER_PATH=$2
		shift
		;;
	-q|--quiet)
		NOQUIET=false
		QUIET_OPTION='-q'
		;;
	*)
		>&2 echo "Invalid option '$1'. Use --help to see the valid options"
		exit 1
		;;
	esac
	shift
done

readonly $STCOMMAND="svn st -u \"$SERVER_PATH\";"
readonly $UPCOMMAND="svn up $QUIET_OPTION \"$SERVER_PATH\";"

REPLY=false
if [ $CONFIRM ]; then
	$NOQUIET && echo 'ssh '"$SSH_CONNECTION"' -t '"$STCOMMAND"
	ssh $SSH_CONNECTION -t "$STCOMMAND"
	read -p "Are you sure? [y]" -n 1 -r
fi

if [ $CONFIRM = false ] || [[ $REPLY =~ ^[y]$ ]]; then
	$NOQUIET && echo 'ssh '"$SSH_CONNECTION"' -t '"$UPCOMMAND"
	ssh $SSH_CONNECTION -t "$UPCOMMAND"
fi
