#!/bin/bash

set -e
set -u
set -o pipefail

function show_help {
readonly SCRIPT_NAME=$(basename "$0")
cat <<EOF
Usage: $SCRIPT_NAME [options]
Updates a remote svn working copy directory showing a diff and asking for confirmation.
Allows to ssh into the server directory as an alternative.

-h --help				shows this help message.
-y --skip-confirm 		option executes svn up without confirmation
-s --ssh-connection		ssh server login string, ie: example@example.com
-p --server-path 		path to the regular file or directory to be updated
-q --quiet				print only essential information and errors

EOF
}

#default options
declare SSH_CONNECTION=''
declare SERVER_PATH=''
declare CONFIRM=true
declare NOQUIET=true

while [ "$#" -gt 0 ]
do
	case "$1" in
	-h|--help)
		show_help
		exit 0
		;;
	-y|--skip-confirm)
		CONFIRM=false
		;;
	-s|--ssh-connection)
		SSH_CONNECTION=$2
		shift
		;;
	-p|--server-path)
		SERVER_PATH=$2
		shift
		;;
	-q|--quiet)
		NOQUIET=false
		QUIET_OPTION='-q'
		;;
	*)
		>&2 echo "Invalid option '$1'. Use --help to see the valid options" >&2
		exit 1
		;;
	esac
	shift
done

readonly $DIR=$(dirname $SERVER_PATH)
readonly $FILE=$(basename $SERVER_PATH)
readonly $STCOMMAND="cd \"$DIR\"; svn st -u \"$FILE\";"
readonly $UPCOMMAND="cd \"$DIR\"; svn st -u \"$FILE\";"
readonly $LOGINCOMMAND="cd \"$DIR\"; `echo $SHELL --login`"

$NOQUIET && echo 'ssh '"$SSH_CONNECTION"' -t '"$STCOMMAND"
$NOQUIET && ssh $SSH_CONNECTION -t "$STCOMMAND"

if [ $CONFIRM = false ]; then
	$NOQUIET && echo 'ssh '"$SSH_CONNECTION"' -t '"$UPCOMMAND"
	ssh $SSH_CONNECTION -t "$UPCOMMAND"
	exit 0
fi

declare UPDATED=false
while true; do
	if [ $UPDATED ]; then
		read -p "What do you want to do? [s] log into server, [q] exit " -n 1 -r
	else
		read -p "What do you want to do? [u] svn up server, [s] log into server, [q] exit " -n 1 -r
	fi

	echo
	case "$REPLY" in
	u)
		if [ $UPDATED = false]; then
			$NOQUIET && echo 'ssh '"$SSH_CONNECTION"' -t '"$UPCOMMAND"
			ssh $SSH_CONNECTION -t "$UPCOMMAND"
			$UPDATED=true
		fi
		;;
	s)
		$NOQUIET && echo 'ssh '"$SSH_CONNECTION"' -t '"$LOGINCOMMAND"
		ssh $SSH_CONNECTION -t "$LOGINCOMMAND"
		exit 0
		;;
	q)
		exit 0
		;;
	esac
done
